security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$FR2eV8oFPBWBd7QsbxgITu63mvFBOew8LQYfE2mXaXXS/BsBnVGae'
                        roles: ['ROLE_ADMIN']
                    user:
                        password: '$2y$13$I/fc6ndhZYB3QNRlOf6JS.dmN5IlFnSg5BWnciEFQlIhtf.F8XUuy'
                        roles: ['ROLE_USER']

    firewalls:
        main:
            lazy: true
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
                default_target_path: accueil
            logout:
                path: logout
            custom_authenticator: App\Security\MediatekAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }