jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "ssh-mediatek.alwaysdata.net"
          username: "mediatek"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "bash ~/deploy.sh"
